/**
 * Autogenerated by Thrift Compiler (0.17.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.donnie4w.tldb.tlcli;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class tlcliConstants {

  public static final int ERR_UNDEFINED = 1300;

  public static final int ERR_AUTH_NOPASS = 1301;

  public static final int ERR_TIMEOUT = 506;

  public static final int ERR_NO_MATCH_PARAM = 401;

  public static final int ERR_TABLE_EXIST = 409;

  public static final int ERR_DATA_NOEXIST = 410;

  public static final int ERR_TABLE_NOEXIST = 411;

  public static final int ERR_COLUMN_NOEXIST = 412;

  public static final int ERR_IDX_NOEXIST = 413;

}
